# syntax=docker/dockerfile:1
ARG NODE_VERSION=23

FROM node:${NODE_VERSION}-alpine
ENV NODE_ENV development
WORKDIR /app/frontend

RUN --mount=type=bind,source=package.json,target=package.json \
  --mount=type=bind,source=package-lock.json,target=package-lock.json \
  npm ci

COPY . .
EXPOSE 3000

CMD npm run dev
